### ISSUE TITLE
Change name of folder

### ISSUE THREAD

**Issue by ludovicandrieux** [eckucukoglu/redmine-issue-statistics#15]
Hi,

When we clone git, we get a folder name redmine-issue-statistics and we put it in folder plugins.
But in reality, folder have to be "issuestats". 
There is no doc and it's not really a good way to do installation so can you change your name internaly to become redmine-issue-statistics ?

Thanks
Ludovic

**Comment by eckucukoglu** [comment]
you are exactly right, it was my fault, and i did it for all my redmine plugins, unfortunately, sorry. 

https://github.com/eckucukoglu/redmine-attachable-items
https://github.com/eckucukoglu/redmine-reminder-emails
https://github.com/eckucukoglu/redmine-hack-journals

i wrote some notes and readme for one of them and try to explain installation process, however, for this one, it needs a rewrite.

**Comment by ludovicandrieux** [comment]
Hi,

Thanks for your response.
I use lots of redmine plugins and the "standard" is to clone a git repository with the same name. I don't think lots of people take time to read documentation :(
Imho, it should better to change the name of your repo GIT or to change the folder name to use redmine-timesheet-plugin, not to update the documentation.
But it's just my humble opinion.

Ludovic
