### ISSUE TITLE
Redmine 3.1.0 - missing translation after install

### ISSUE THREAD

**Issue by arnisjuraga** [eckucukoglu/redmine-issue-statistics#16]
![image](https://cloud.githubusercontent.com/assets/2185289/21443141/80bd3044-c8ab-11e6-86f9-27914d352ef3.png)

**Comment by gsgs726** [comment]
Hello, I am experiencing this same error - has it been debugged?

**Comment by swiehr** [comment]
Found the problem:
It is not mentioned anywhere but the folder of the plugin must be named "issuestats" (as the plugin is registered in init.rb) and NOT redmine-issue-statistics

so:
`git clone https://github.com/eckucukoglu/redmine-issue-statistics issuestats`

**Comment by eckucukoglu** [comment]
yeap, both swiehr and arnisjuraga are right. i wrote a small note on readme.

just clone to issuestats folder, not redmine-issue-statistics
